### PR TITLE
Fix behavior of "last" indicator

### LINKED ISSUE #14: Behavior of "last" indicator
As I understand it, the "last" indicator in the top left is supposed to show the most recent value. However, at the moment, it shows the *oldest* value still in the buffer:

image

If this is in fact unintended behaviour, I can try my hand at a fix.

### PR DESCRIPTION
**Pull request by svetter**
Indicator labeled "last" in top left corner now shows the most recent value instead of the oldest one.

Also, the label now reads "current" instead of "last" to remove ambiguity.

Fixes #14

### CODE REVIEW

File: src/ringbuffer.rs [hunk 1]
```diff
@@ -25,11 +30,13 @@ impl<T: Copy + Default> FixedRingBuffer<T> {
         // already reduced memory allocation with larger buffer
         if self.buf.len() == self.buf.capacity() {
             let len = self.buf.len();
+            // Overwrite older values by shifting left
             self.buf.copy_within(self.head + 1..len, 0);
+            // Truncate vector
             self.buf.resize(self.cap - 1, Default::default());
             self.head = 0;
         }
-        self.buf.push(elem);
```
Comment (svetter) [inline src/ringbuffer.rs:32]: Hold on, this line obviously should not have been removed. Having some problems with the repo, I'll fix this in a bit

**Review by aantn — APPROVED** [review]
